DROP TABLE IF EXISTS STUDENT_INFO;
  
CREATE TABLE STUDENT_INFO (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  STUDENT_NAME VARCHAR(250) NOT NULL,
  STUDENT_CLASS VARCHAR(250) NOT NULL,
  STUDENT_SECTION VARCHAR(250) DEFAULT NULL,
   STUDENT_TERM_1 BIT;
   STUDENT_TERM_2 BIT;
   STUDENT_TERM_3 BIT;
);